### PR TITLE
add messageReplyOption to endpoint to support threaded replies

### PR DESCRIPTION
**Pull request by alexandermarston**

### CODE REVIEW

**Comment by mr-karan** [comment]
This looks useful. Thanks!

**Comment by alexandermarston** [comment]
Thanks @mr-karan - would you mind cutting a release with this?

**Comment by mr-karan** [comment]
https://github.com/mr-karan/calert/releases/tag/v2.1.0

**Comment by jonathan-correa-paiva** [comment]
Threaded replays needs to have a threadKey to send the same alert to the same "conversation", Maybe you could use the fingerprint to manage threadKeys, because, in a Room cnveted to conversarions, generates a new Thread every in every notification.

Instead of sending the thread name, it's needs to send a threadKey in the thread object.

Maybe I need to do another config or something, but I've implemented the same in jenkins and I needed to change the object of thread to threadKey: "newKey" in this case we could use the fingerprint.

**Pull request merged**
