### PR TITLE
send 7 alerts in one message at the maximum

### PR DESCRIPTION
**Pull request by jackge007**

### CODE REVIEW

**Comment by jackge007** [comment]
When send too many alerts in one message, these alerts may lost in chat room since the limitation in Google Chat.
ERR: 2019/12/10 07:30:57 /calert/main.go:44: Error while processing request: Error while sending alert
ERR: 2019/12/10 07:30:58 /calert/notification.go:48: Error sending alert Webhook API error: {
  "error": {
    "code": 400,
    "message": "Message is longer than 4096 characters",
    "status": "INVALID_ARGUMENT"
  }
}

**Comment by jackge007** [comment]
@mr-karan @wagdav  Need your review and approve

**Comment by mr-karan** [comment]
What's the calculation behind arriving at `7` alerts?

**Comment by mr-karan** [comment]
Closing as solved by https://github.com/mr-karan/calert/pull/10

**Pull request closed without merging**
